/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'agent-configs': AgentConfig;
    'agent-runtime-logs': AgentRuntimeLog;
    'aid-applications': AidApplication;
    'case-reviews': CaseReview;
    'public-projects': PublicProject;
    'donation-intentions': DonationIntention;
    'feedback-reports': FeedbackReport;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'agent-configs': AgentConfigsSelect<false> | AgentConfigsSelect<true>;
    'agent-runtime-logs': AgentRuntimeLogsSelect<false> | AgentRuntimeLogsSelect<true>;
    'aid-applications': AidApplicationsSelect<false> | AidApplicationsSelect<true>;
    'case-reviews': CaseReviewsSelect<false> | CaseReviewsSelect<true>;
    'public-projects': PublicProjectsSelect<false> | PublicProjectsSelect<true>;
    'donation-intentions': DonationIntentionsSelect<false> | DonationIntentionsSelect<true>;
    'feedback-reports': FeedbackReportsSelect<false> | FeedbackReportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'reviewer' | 'coordinator' | 'viewer';
  organizationName: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-configs".
 */
export interface AgentConfig {
  id: number;
  configName: string;
  isActive?: boolean | null;
  provider: 'openai_compatible' | 'deepseek' | 'qwen' | 'ollama' | 'custom';
  /**
   * 填写 OpenAI 兼容接口地址，例如 https://api.openai.com/v1 或本地模型网关地址。
   */
  baseUrl: string;
  /**
   * 仅后台服务端调用大模型时使用。不要把此字段传给前台页面、公开 API 或日志。
   */
  apiKey: string;
  modelName: string;
  temperature: number;
  maxOutputTokens: number;
  timeoutSeconds: number;
  /**
   * 后续细调四辨审核 Agent 时优先从这里读取基础提示词。
   */
  systemPrompt?: string | null;
  /**
   * 记录供应商账号、使用范围、测试结论或切换说明，避免填写无关敏感信息。
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runtime-logs".
 */
export interface AgentRuntimeLog {
  id: number;
  toolName: string;
  safety: 'read' | 'write';
  success: boolean;
  durationMs: number;
  /**
   * 已脱敏和截断，不存储 API Key、Token、密码等敏感字段。
   */
  argsPreview?: string | null;
  /**
   * 已脱敏和截断，仅用于审计工具行为。
   */
  resultPreview?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aid-applications".
 */
export interface AidApplication {
  id: number;
  patientAlias: string;
  applicantRole: 'family' | 'patient' | 'volunteer' | 'institution_staff';
  diseaseSummary: string;
  treatmentStage: string;
  region: string;
  expenseTotal: number;
  paidAmount: number;
  reimbursementEstimate: number;
  remainingGap: number;
  familyBurden: string;
  requestedNeeds:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  materialNotes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  evidence:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rawNarrative: string;
  consentForInstitutionReview?: boolean | null;
  consentForDeidentifiedDisplay?: boolean | null;
  status: 'draft' | 'submitted' | 'needs_materials' | 'under_review' | 'approved' | 'rejected' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-reviews".
 */
export interface CaseReview {
  id: number;
  reviewTitle: string;
  application: number | AidApplication;
  goodAndHarm:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  truth:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  scaleUrgency: 'low' | 'medium' | 'high';
  scaleRationale: string;
  resourceGap: number;
  proximity:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  humanChecklist:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  decision?: ('request_materials' | 'reject' | 'approve_display' | 'offline_follow_up') | null;
  reviewSource: 'deterministic' | 'local_llm' | 'manual';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-projects".
 */
export interface PublicProject {
  id: number;
  application?: (number | null) | AidApplication;
  slug: string;
  patientAlias: string;
  diseaseLabel: string;
  region: string;
  status: 'urgent' | 'in_treatment' | 'awaiting_materials' | 'receiving_intentions' | 'completed';
  verifiedNeed: string;
  resourceGap: number;
  matchedIntentions: number;
  needs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  progress:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  story: string;
  evidenceSummary:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  feedback:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-intentions".
 */
export interface DonationIntention {
  id: number;
  project?: (number | null) | PublicProject;
  helpCategory: 'money' | 'materials' | 'services';
  helpType:
    | 'funding_intention'
    | 'medical_resource'
    | 'drug_resource'
    | 'nutrition'
    | 'accommodation'
    | 'transportation'
    | 'volunteer'
    | 'policy_consultation'
    | 'psychological_support'
    | 'propagation'
    | 'corporate_support';
  amountOrResource: string;
  city: string;
  contact: string;
  receiptNeed?: boolean | null;
  message?: string | null;
  classification?: string | null;
  matchedNeedLabels?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  followUpScript?: string | null;
  status: 'new' | 'matched' | 'contacted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-reports".
 */
export interface FeedbackReport {
  id: number;
  title: string;
  project: number | PublicProject;
  intention?: (number | null) | DonationIntention;
  draft: string;
  requiresInstitutionReview?: boolean | null;
  status: 'draft' | 'reviewed' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'agent-configs';
        value: number | AgentConfig;
      } | null)
    | ({
        relationTo: 'agent-runtime-logs';
        value: number | AgentRuntimeLog;
      } | null)
    | ({
        relationTo: 'aid-applications';
        value: number | AidApplication;
      } | null)
    | ({
        relationTo: 'case-reviews';
        value: number | CaseReview;
      } | null)
    | ({
        relationTo: 'public-projects';
        value: number | PublicProject;
      } | null)
    | ({
        relationTo: 'donation-intentions';
        value: number | DonationIntention;
      } | null)
    | ({
        relationTo: 'feedback-reports';
        value: number | FeedbackReport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  organizationName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-configs_select".
 */
export interface AgentConfigsSelect<T extends boolean = true> {
  configName?: T;
  isActive?: T;
  provider?: T;
  baseUrl?: T;
  apiKey?: T;
  modelName?: T;
  temperature?: T;
  maxOutputTokens?: T;
  timeoutSeconds?: T;
  systemPrompt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runtime-logs_select".
 */
export interface AgentRuntimeLogsSelect<T extends boolean = true> {
  toolName?: T;
  safety?: T;
  success?: T;
  durationMs?: T;
  argsPreview?: T;
  resultPreview?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aid-applications_select".
 */
export interface AidApplicationsSelect<T extends boolean = true> {
  patientAlias?: T;
  applicantRole?: T;
  diseaseSummary?: T;
  treatmentStage?: T;
  region?: T;
  expenseTotal?: T;
  paidAmount?: T;
  reimbursementEstimate?: T;
  remainingGap?: T;
  familyBurden?: T;
  requestedNeeds?: T;
  materialNotes?: T;
  evidence?: T;
  rawNarrative?: T;
  consentForInstitutionReview?: T;
  consentForDeidentifiedDisplay?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-reviews_select".
 */
export interface CaseReviewsSelect<T extends boolean = true> {
  reviewTitle?: T;
  application?: T;
  goodAndHarm?: T;
  truth?: T;
  scaleUrgency?: T;
  scaleRationale?: T;
  resourceGap?: T;
  proximity?: T;
  humanChecklist?: T;
  decision?: T;
  reviewSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-projects_select".
 */
export interface PublicProjectsSelect<T extends boolean = true> {
  application?: T;
  slug?: T;
  patientAlias?: T;
  diseaseLabel?: T;
  region?: T;
  status?: T;
  verifiedNeed?: T;
  resourceGap?: T;
  matchedIntentions?: T;
  needs?: T;
  progress?: T;
  story?: T;
  evidenceSummary?: T;
  feedback?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-intentions_select".
 */
export interface DonationIntentionsSelect<T extends boolean = true> {
  project?: T;
  helpCategory?: T;
  helpType?: T;
  amountOrResource?: T;
  city?: T;
  contact?: T;
  receiptNeed?: T;
  message?: T;
  classification?: T;
  matchedNeedLabels?: T;
  followUpScript?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-reports_select".
 */
export interface FeedbackReportsSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  intention?: T;
  draft?: T;
  requiresInstitutionReview?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}