import type { AidApplication, DonationIntention, PublicProject, ResourceNeed } from './types';

export const demoNeeds: ResourceNeed[] = [
  {
    id: 'need-treatment-cost',
    type: 'treatment_cost',
    category: 'money',
    label: '治疗费用缺口',
    description: '巩固治疗阶段仍有约10万元费用缺口，需要机构核验后对接资金支持意向。',
    priority: 'high',
  },
  {
    id: 'need-transportation',
    type: 'transportation',
    category: 'services',
    label: '复诊交通协助',
    description: '家庭异地就医，后续复诊需要交通安排、陪同和属地志愿者协作。',
    priority: 'medium',
  },
  {
    id: 'need-policy-consultation',
    type: 'policy_consultation',
    category: 'services',
    label: '医保/救助政策咨询',
    description: '报销状态不清，需要志愿者或机构工作人员协助梳理政策路径。',
    priority: 'high',
  },
  {
    id: 'need-nutrition',
    type: 'nutrition',
    category: 'materials',
    label: '治疗期营养支持',
    description: '治疗期间需要符合医嘱范围的营养支持信息，由机构核验后对接。',
    priority: 'medium',
  },
];

export const demoAidApplication: AidApplication = {
  id: 'case-leukemia-child-a',
  patientAlias: '患儿A',
  applicantRole: 'family',
  disease: '儿童急性淋巴细胞白血病',
  treatmentStage: '诱导治疗后进入巩固治疗准备期',
  hospitalRegion: '华南地区某三甲医院',
  expenseTotal: 318000,
  paidAmount: 126000,
  reimbursementEstimate: 92000,
  remainingGap: 100000,
  familyBurden: '家庭主要收入来自父亲零工，母亲陪护停工，已有亲友借款。',
  requestedNeeds: demoNeeds,
  materialNotes: [
    '模拟诊断摘要已提供',
    '住院费用清单已提供',
    '医保报销预估说明不完整',
    '最新发票缺失',
    '监护关系证明未上传',
  ],
  evidence: [
    {
      id: 'evidence-diagnosis',
      label: '模拟诊断摘要',
      status: 'received',
      note: '显示疾病类型与治疗阶段，用于机构复核。',
    },
    {
      id: 'evidence-expense-list',
      label: '住院费用清单',
      status: 'conflicting',
      note: '费用清单与叙事中的其中一笔金额需要人工核对。',
    },
    {
      id: 'evidence-reimbursement',
      label: '医保/商保报销状态',
      status: 'needs_manual_check',
      note: '当前只有预估，没有确认回执。',
    },
    {
      id: 'evidence-latest-invoice',
      label: '最新医疗费用发票',
      status: 'missing',
      note: '缺少最新发票，无法确认当前费用缺口。',
    },
    {
      id: 'evidence-guardian-proof',
      label: '监护关系证明',
      status: 'missing',
      note: '儿童救助申请需要确认申请人与患儿关系。',
    },
  ],
  rawNarrative:
    '患儿A正在接受白血病治疗，家庭已承担前期费用。叙事草稿中曾出现学校、病房楼层等可识别信息，需脱敏后才能展示。家属也提到比起单一现金帮助，更希望有人协助确认报销政策、复诊交通和治疗期营养支持。',
  consentForInstitutionReview: true,
  consentForDeidentifiedDisplay: true,
  status: 'under_review',
};

export const seedPublicProjects: PublicProject[] = [
  {
    id: 'project-child-a',
    patientAlias: '患儿A',
    disease: '急性淋巴细胞白血病',
    status: 'receiving_intentions',
    region: '华南',
    verifiedNeed: '巩固治疗阶段费用缺口与政策咨询',
    resourceGap: 100000,
    matchedIntentions: 6,
    needs: demoNeeds.filter((need) =>
      ['need-treatment-cost', 'need-policy-consultation', 'need-transportation'].includes(need.id),
    ),
    progress: ['机构已完成初审', '等待补充最新发票', '已匹配2名本地志愿者'],
    story:
      '患儿A正在接受规范治疗，家庭已完成前期自筹和医保申请。项目当前重点是补齐费用证明，并匹配后续治疗阶段的钱、物、服社会支持。',
    evidenceSummary: ['模拟诊断摘要已核对', '费用清单需与最新发票复核', '公开故事已完成脱敏'],
    feedback: ['已记录阶段性进展', '反馈草稿需机构工作人员复核后公开'],
  },
  {
    id: 'project-parent-b',
    patientAlias: '患者B',
    disease: '重症再生障碍性贫血',
    status: 'in_treatment',
    region: '华东',
    verifiedNeed: '移植前支持治疗与陪护资源',
    resourceGap: 68000,
    matchedIntentions: 3,
    needs: [
      {
        id: 'need-drug-resource',
        type: 'medicine',
        category: 'materials',
        label: '药品资源信息',
        description: '需要机构确认可合规对接的药品资源信息。',
        priority: 'medium',
      },
      {
        id: 'need-escort-b',
        type: 'escort',
        category: 'services',
        label: '陪诊志愿者',
        description: '移植前检查频繁，需要本地志愿者协助陪诊和交通衔接。',
        priority: 'medium',
      },
    ],
    progress: ['医院社工已复核病情摘要', '药品资源意向待确认'],
    story: '患者B处于移植前准备阶段，机构正在协调治疗费用缺口、药品信息和陪护支持。',
    evidenceSummary: ['医院社工完成病情摘要复核', '药品资源需确认合法来源'],
    feedback: ['药品资源意向正在由机构联系确认'],
  },
  {
    id: 'project-child-c',
    patientAlias: '患儿C',
    disease: '罕见病长期治疗',
    status: 'completed',
    region: '西南',
    verifiedNeed: '阶段性药品与复查交通支持',
    resourceGap: 0,
    matchedIntentions: 9,
    needs: [
      {
        id: 'need-follow-up-transportation',
        type: 'transportation',
        category: 'services',
        label: '复查交通提醒',
        description: '阶段性援助完成后继续记录复查交通需求。',
        priority: 'low',
      },
    ],
    progress: ['阶段援助已完成', '反馈报告已生成', '后续复查提醒已登记'],
    story: '患儿C已完成本阶段救助，机构已生成脱敏反馈报告并继续跟进复查。',
    evidenceSummary: ['阶段援助记录齐全', '反馈报告不含可识别隐私'],
    feedback: ['阶段性反馈报告已生成', '后续复查交通需求持续跟进'],
  },
];

export const seedDonationIntentions: DonationIntention[] = [
  {
    id: 'intent-seed-1',
    projectId: 'project-child-a',
    helpCategory: 'money',
    helpType: 'funding_intention',
    amountOrResource: '愿意支持5000元，由机构联系确认',
    city: '深圳',
    contact: 'contact@example.org',
    receiptNeed: true,
    message: '希望收到阶段反馈',
    status: 'new',
  },
  {
    id: 'intent-seed-2',
    projectId: 'project-child-a',
    helpCategory: 'services',
    helpType: 'policy_consultation',
    amountOrResource: '可提供医保和属地救助政策咨询',
    city: '深圳',
    contact: 'volunteer@example.com',
    receiptNeed: false,
    message: '周末可协助家属整理材料',
    status: 'matched',
  },
];
